files:
  - source: /src/main/resources/assets/modmenu/lang/en_us.json
    translation: /src/main/resources/assets/modmenu/lang/%locale%.json
    skip_untranslated_strings: true
    skip_untranslated_files: true

