# This action synchronizes translations with Crowdin:
# - new source strings from en_us.json are uploaded
# - new translations added in Crowdin are downloaded
#   - if translations were downloaded a pull request is created
# 
# Adding a new branch:
# - add branch to matrix
# - manually run the action once to initialize the new branch on Crowdin
# - make sure Crowdin knows about the new branch

name: Crowdin

# can be run manually
# also automatically runs once a week (only on the default branch)
on:
  workflow_dispatch: ~
  schedule:
    - cron: 1 2 * * 3 # At 02:01 on Wednesday.

jobs:
  crowdin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["1.17", "1.18", "1.19"]
    steps:
    - uses: actions/checkout@v2
    - uses: crowdin/github-action@1.4.9
      with:
        upload_sources: true

        download_translations: true
        skip_untranslated_strings: true

        source: src/main/resources/assets/modmenu/lang/en_us.json
        translation: src/main/resources/assets/modmenu/lang/%locale%.json
        # locale/language mappings must be added in Crowdin
        # see https://github.com/jackassmc/minecraft-crowdin-languages

        crowdin_branch_name: ${{ matrix.branch }}
        localization_branch_name: l10n_${{ matrix.branch }}
        pull_request_base_branch_name: ${{ matrix.branch }}

        pull_request_title: Update ${{ matrix.branch }} translations
        commit_message: |
          Update ${{ matrix.branch }} translations

          - Update translations

        project_id: 520764
        token: ${{ secrets.CROWDIN_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
