# This action synchronizes translations with Crowdin:
# - new source strings from en_us.json are uploaded
# - new translations committed directly to other language files are uploaded
# - new translations added in Crowdin are downloaded
#   - if translations were downloaded a pull request is created
# 
# Adding a new branch:
# - update the branch env var
# - run the action on the new branch once to initialize the new branch on Crowdin
# - make sure Crowdin knows about the new branch

name: Crowdin

# can be run manually
# also automatically runs once a day at 02:01
on:
  workflow_dispatch: ~
  schedule:
    - cron: "1 2 * * *"

# crowdin translations cannot be built concurrently
concurrency: crowdin

jobs:
  crowdin:
    runs-on: ubuntu-latest
    env:
      branch: "1.19"
    steps:
    - uses: actions/checkout@v2
    - uses: crowdin/github-action@1.4.9
      with:
        upload_sources: true
        upload_translations: true

        download_translations: true
        skip_untranslated_strings: true

        source: src/main/resources/assets/modmenu/lang/en_us.json
        translation: src/main/resources/assets/modmenu/lang/%locale%.json
        # locale/language mappings must be added in Crowdin
        # see https://github.com/jackassmc/minecraft-crowdin-languages

        pull_request_title: Update ${{ env.branch }} translations
        commit_message: |
          Update ${{ env.branch }} translations

          - Update translations
        localization_branch_name: l10n_${{ env.branch }}
        crowdin_branch_name: ${{ env.branch }}

        project_id: 520764
        token: ${{ secrets.CROWDIN_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
